apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ph6h0cg0r-java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ph6h0cg0r-java-springboot 
  name: ph6h0cg0r-java-springboot
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ph6h0cg0r-java-springboot
    weight: 100 
