apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ph6h0cg0r-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:dfdcaa9bf2975d92b72f33b90233fde7521666ad@sha256:4bf7a2f226bc2ce863a2db5c153cb24566940b6155f61cd6a8b176fb4703b524
          name: container-image
